Repository fluentis-doc/FluentisErp, pull requests merged in 2024-11, with the labels that each got.

#210 json translations
  i18n/ro-RO/code.json
  i18n/ro-RO/docusaurus-plugin-content-docs/current.json
  i18n/ro-RO/docusaurus-theme-classic/footer.json
Labels: ro-RO, translation

#219 Translate en-US applications-general
  i18n/en-US/docusaurus-plugin-content-docs/current/applications/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/applications/applications-intro.md
  i18n/en-US/docusaurus-plugin-content-docs/current/applications/arm-intro.md
  i18n/en-US/docusaurus-plugin-content-docs/current/applications/audit-trail.md
  i18n/en-US/docusaurus-plugin-content-docs/current/applications/business-intelligence.md
  i18n/en-US/docusaurus-plugin-content-docs/current/applications/document-manager.md
Labels: en-US, translation

#246 planning
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/planning-intro.md
Labels: en-US, translation

#253 planning/mps-master-production-scheduling/reports
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/reports/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/reports/job-orders-progress-control.md
Labels: en-US, translation

#256 modification translation
  i18n/hr-HR/docusaurus-plugin-content-docs/current/configurations/parameters/employees/staff-management.md
Labels: documentation

#257 planning
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/planning-intro.md
Labels: ro-RO, translation

#271 planning/capacity-requirements-planning/phase-sequences
  i18n/hr-HR/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/phase-sequences/phase-sequence-topdown.md
Labels: hr-HR, translation

#267 planning Review this en file job-orders-progress-control.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/reports/job-orders-progress-control.md
Labels: en-US, translation

#272 planning/master-production-schedule
  i18n/hr-HR/docusaurus-plugin-content-docs/current/planning/master-production-schedule/mps-items.md
Labels: hr-HR, translation

#255 planning/ms-master-scheduling/planned-orders
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/new-planned-order.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/procedures/release-planned-orders.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/procedures/view-grouping.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/reports.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/search-planned-orders.md
Labels: en-US, translation

#254 planning/ms-master-scheduling
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/phase-sequences/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/phase-sequences/phase-sequence-topdown.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/phase-sequences/phase-sequence.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/reports/job-orders-progress-control.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/finite-capacityscheduling.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/general-schedule.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/mrp.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/ms-master-scheduling-intro.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/new-planned-order.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/procedures/release-planned-orders.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/procedures/view-grouping.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/planning-intro.md
Labels: en-US, translation

#248 planning/capacity-requirements-planning/gantt-visualization
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/gantt-visualization/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/gantt-visualization/gantt-new.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/gantt-visualization/gantt-visualization-intro.md
Labels: en-US, translation

#247 planning/capacity-requirements-planning
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/capacity-requirements-planning-intro.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/work-center-capacity.md
Labels: en-US, translation

#252 planning/mps-master-production-scheduling/production-job-orders
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/production-job-orders/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/production-job-orders/job-orders-detail.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/production-job-orders/job-orders.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/production-job-orders/new-monoproduct-job-order.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/production-job-orders/new-multiproduct-job-order.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/production-job-orders/valorization.md
Labels: en-US, translation

#378 finance-area
  i18n/hr-HR/docusaurus-plugin-content-docs/current/finance-area/finance-intro.md
Labels: hr-HR, translation

#375 finance-area/sdi-documents
  i18n/hr-HR/docusaurus-plugin-content-docs/current/finance-area/sdi-documents/outgoing-foreign-purchase-documents.md
  i18n/hr-HR/docusaurus-plugin-content-docs/current/finance-area/sdi-documents/outgoing-sales-documents.md
Labels: hr-HR, translation

#372 finance-area/professional-men
  i18n/hr-HR/docusaurus-plugin-content-docs/current/finance-area/professional-men/general-overview.md
Labels: hr-HR, translation

#251 planning/mps-master-production-scheduling
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/phase-sequences/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/phase-sequences/phase-sequence-topdown.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/capacity-requirements-planning/phase-sequences/phase-sequence.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/master-production-schedule/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/master-production-schedule/mps-items.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/job-order-creation.md
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/job-orders-intro.md
Labels: en-US, translation

#250 planning/master-production-schedule
  i18n/en-US/docusaurus-plugin-content-docs/current/planning/master-production-schedule/mps-items.md
Labels: en-US, translation

#370 finance-area/maturity-values/procedures
  i18n/hr-HR/docusaurus-plugin-content-docs/current/finance-area/maturity-values/procedures/generation-of-dunning-letters/generation-of-dunning-letters-intro.md
Labels: hr-HR, translation

#412 Automated PR: Sync website-edits with main
  docs/crm/home-crm/contacts/new-contact/contact-zone.md
Labels: auto

#416 Automated PR: Sync website-edits with main
  docs/crm/home-crm/contacts/new-contact/contact-agents.md
  docs/crm/home-crm/contacts/new-contact/contact-visit-reports.md
Labels: auto

#424 Automated PR: Sync website-edits with main
  i18n/ro-RO/docusaurus-plugin-content-docs/current/crm/chance/opportunity.map.md
Labels: auto

#411 finance-area/sdi-documents
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/sdi-documents/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/sdi-documents/incoming-purchase-documents.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/sdi-documents/outgoing-foreign-purchase-documents.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/sdi-documents/outgoing-sales-documents.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/sdi-documents/purchase-invoice-creation-from-xml.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/sdi-documents/sdi-documents-intro.md
Labels: en-US, translation

#369 finance-area/maturity-values/maturity-values
  i18n/hr-HR/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/difference-between-maturity-value-and-ledger-balance.md
  i18n/hr-HR/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/maturity-values/maturity-values-management.md
  i18n/hr-HR/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/maturity-values/search-maturity-values.md
Labels: hr-HR, translation

#410 finance-area/professional-men/search-compensations
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/search-compensations/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/search-compensations/search-compensations-intro.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/search-compensations/withholding-tax-paying-in.md
Labels: en-US, translation

#408 finance-area/professional-men/procedures
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/procedures/calculate-commissions.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/procedures/model-f24/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/procedures/model-f24/f24-management.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/procedures/model-f24/f24-model.md
Labels: en-US, translation

#404 finance-area/particular-cases
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/particular-cases/VAT_regime-del-maine.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/particular-cases/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/particular-cases/agricultural-VAT.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/particular-cases/mixed-reverse-charge.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/particular-cases/suspended-VAT.md
Labels: en-US, translation

#407 finance-area/professional-men/compensations-management
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/compensations-management/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/compensations-management/compensations-management-intro.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/compensations-management/cost-profit-centres.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/compensations-management/national-insurance.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/compensations-management/payments-list.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/compensations-management/total-withholding-tax.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/compensations-management/vat-summaries.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/compensations-management/withholding-tax-paying-in.md
Labels: en-US, translation

#266 planning/ms-master-scheduling/planned-orders
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/new-planned-order.md
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/procedures/_category_.json
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/procedures/release-planned-orders.md
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/procedures/view-grouping.md
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/reports.md
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/planned-orders/search-planned-orders.md
Labels: ro-RO, translation

#406 finance-area/professional-men/accounting
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/compensation-accounting/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/compensation-accounting/compensations-accounting.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/compensation-accounting/filter.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/compensation-accounting/rollback.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/enasarco-accounting/acquisition.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/enasarco-accounting/enasarco-accounting-intro.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/enasarco-accounting/previous.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/payments-accounting/filter.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/payments-accounting/parameters.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/payments-accounting/payments-accounting-intro.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/accounting/payments-accounting/previous.md
Labels: en-US, translation

#405 finance-area/professional-men
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/general-overview.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/professional-men/tables-and-parameters.md
Labels: en-US, translation

#403 finance-area/maturity-values/reports
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/reports/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/reports/account-statement-on-open-maturity-values.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/reports/aging-report-customer-vendor.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/reports/customer-vendor-due-register.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/reports/difference-between-maturity-value-and-ledger-balance.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/reports/dunning-letters.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/reports/maturity-value-grouping.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/reports/maturity-value-list.md
Labels: en-US, translation
