Repository fluentis-doc/FluentisErp, pull requests merged in 2024-12, with the labels that each got.

#265 planning/ms-master-scheduling
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/reports/_category_.json
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/reports/job-orders-progress-control.md
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/_category_.json
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/finite-capacityscheduling.md
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/general-schedule.md
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/mrp.md
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/ms-master-scheduling/ms-master-scheduling-intro.md
Labels: ro-RO, translation

#264 planning/mps-master-production-scheduling/reports
  i18n/ro-RO/docusaurus-plugin-content-docs/current/planning/mps-master-production-scheduling/reports/job-orders-progress-control.md
Labels: ro-RO, translation

#442 review and add purchase order
  docs/purchase/purchase-flow/measurement-units.md
  docs/purchase/purchase-job-order/general-overview.md
  docs/purchase/purchase-job-order/insert-purchase-job-order/header.md
  docs/purchase/purchase-orders/general-overview.md
  docs/purchase/purchase-orders/insert-purchase-orders/_category_.json
  docs/purchase/purchase-orders/insert-purchase-orders/header-procedures.md
  docs/purchase/purchase-orders/insert-purchase-orders/header.md
  docs/purchase/purchase-orders/insert-purchase-orders/items.md
  docs/purchase/purchase-orders/insert-purchase-orders/purchase-orders-management.md
  docs/purchase/purchase-orders/insert-purchase-orders/summaries.md
  docs/purchase/purchase-orders/purchase-order.md
  i18n/en-US/docusaurus-plugin-content-docs/current/purchase/purchase-orders/insert-purchase-orders/header.md
  i18n/en-US/docusaurus-plugin-content-docs/current/purchase/purchase-orders/insert-purchase-orders/purchase-orders-management.md
  i18n/fr-FR/docusaurus-plugin-content-docs/current/purchase/purchase-orders/insert-purchase-orders/header.md
  i18n/hr-HR/docusaurus-plugin-content-docs/current/purchase/purchase-orders/insert-purchase-orders/purchase-orders-management.md
  i18n/hr-HR/docusaurus-plugin-content-docs/current/purchase/purchase-orders/search-purchase-orders.md
  i18n/pt-PT/docusaurus-plugin-content-docs/current/purchase/purchase-orders/insert-purchase-orders/header.md
  i18n/ro-RO/docusaurus-plugin-content-docs/current/purchase/purchase-orders/insert-purchase-orders/header.md
  i18n/zh-CN/docusaurus-plugin-content-docs/current/purchase/purchase-orders/insert-purchase-orders/header.md
Labels: it-IT

#401 finance-area/maturity-values/maturity-values
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/commissions.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/difference-between-maturity-value-and-ledger-balance.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/dunned-maturity-values.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/loans-management.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/maturity-value-grouping.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/maturity-values/_category_.json
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/maturity-values/maturity-values-management.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/maturity-values/search-maturity-values.md
  i18n/en-US/docusaurus-plugin-content-docs/current/finance-area/maturity-values/maturity-values/payments.md
Labels: en-US, translation
